import {createHash} from 'node:crypto';
import {db,json,validSignature} from '../_shared.js';
const hash=(x:string)=>createHash('sha256').update(x).digest('hex');
export default async function handler(req:any,res:any){
 if(req.method!=='POST')return json(res,405,{error:'method_not_allowed'});const raw=typeof req.body==='string'?req.body:JSON.stringify(req.body||{});const sig=req.headers['x-linkedstore-hmac-sha256']||req.headers['x-nuvemshop-hmac-sha256'];if(!validSignature(raw,Array.isArray(sig)?sig[0]:sig))return json(res,401,{error:'invalid_signature'});
 const payload=typeof req.body==='string'?JSON.parse(req.body):req.body;const store=String(payload.store_id||payload.store||req.headers['x-linkedstore-store-id']||'');const orderId=String(payload.id||payload.order_id||'');const eventType=String(req.headers['x-linkedstore-topic']||payload.event||'order/paid');const eventKey=String(req.headers['x-linkedstore-event-id']||hash(`${store}:${eventType}:${orderId}:${raw}`));const client=db();
 const {data:evt,error:ie}=await client.from('nuvemshop_webhook_events').upsert({event_key:eventKey,event_type:eventType,store_id:store,resource_id:orderId,payload},{onConflict:'event_key',ignoreDuplicates:true}).select('id,status').maybeSingle();if(ie)return json(res,500,{error:'event_store_failed'});if(!evt)return json(res,200,{ok:true,duplicate:true});
 try{const order={store_id:store,order_id:orderId,order_number:String(payload.number||orderId),payment_status:String(payload.payment_status||payload.status||'paid'),total:Number(payload.total||payload.total_paid||0),completed_at:payload.completed_at||payload.paid_at||new Date().toISOString(),customer_email_hash:payload.contact_email?hash(String(payload.contact_email).toLowerCase().trim()):null,raw_payload:payload,updated_at:new Date().toISOString()};const {data:o,error:oe}=await client.from('tracked_orders').upsert(order,{onConflict:'store_id,order_id'}).select('id').single();if(oe)throw oe;
  const sessionKey=payload.note_attributes?.find?.((x:any)=>x.name==='ecom_session_id')?.value||payload.ecom_session_id;let session=null;if(sessionKey){const r=await client.from('tracking_sessions').select('id,visitor_id').eq('session_key',sessionKey).maybeSingle();session=r.data}
  await client.from('order_attributions').upsert({order_id:o.id,session_id:session?.id||null,visitor_id:session?.visitor_id||null,confidence:session?'exact_session':'unattributed',details:{session_key:sessionKey||null}},{onConflict:'order_id'});
  await client.from('nuvemshop_webhook_events').update({status:'processed',processed_at:new Date().toISOString()}).eq('id',evt.id);return json(res,200,{ok:true});
 }catch(e:any){await client.from('nuvemshop_webhook_events').update({status:'failed',error:String(e?.message||e).slice(0,1000)}).eq('id',evt.id);return json(res,500,{error:'processing_failed'})}
}
