import {useMemo,useState} from 'react';
import {NavLink,Route,Routes,useLocation} from 'react-router-dom';
import {Activity,BarChart3,ChevronDown,Clock3,FileText,LayoutDashboard,Link2,Menu,MousePointerClick,Radio,Search,Settings,ShoppingBag,Tag,Users,X} from 'lucide-react';
import type {AttributionRow,Metric} from './types';

const demo:AttributionRow[]=[
 {id:'1',date:'10 ago, 14:32',order:'#1847',channel:'Meta Ads',campaign:'Volta às aulas',creative:'Mochila Carrossel',revenue:289.9,status:'Atribuída'},
 {id:'2',date:'10 ago, 12:08',order:'#1846',channel:'Google Ads',campaign:'Marca · Pesquisa',creative:'Flora Kids',revenue:179,status:'Atribuída'},
 {id:'3',date:'9 ago, 19:45',order:'#1845',channel:'Direto',campaign:'—',creative:'—',revenue:349.8,status:'Sem UTM'}];
const money=(n:number)=>n.toLocaleString('pt-BR',{style:'currency',currency:'BRL'});

function Card({label,value,delta,tone='green'}:Metric){return <article className="metric"><div className={`metric-icon ${tone}`}>{tone==='green'?<BarChart3/>:<Activity/>}</div><span>{label}</span><strong>{value}</strong>{delta&&<small>{delta}</small>}</article>}
function Empty({title,copy}:{title:string;copy:string}){return <div className="empty"><Radio/><h3>{title}</h3><p>{copy}</p></div>}
function Filters(){return <div className="filters"><button>Últimos 30 dias <ChevronDown/></button><button>Todos os canais <ChevronDown/></button><label><Search/><input placeholder="Buscar campanha..."/></label></div>}
function Overview(){return <><header className="page-title"><div><span>Marketing</span><h1>Visão geral</h1><p>Performance e atribuição de vendas em um só lugar.</p></div><button className="primary">Exportar relatório</button></header><Filters/><section className="metrics"><Card label="Receita atribuída" value="R$ 818,70" delta="3 vendas rastreadas"/><Card label="Sessões" value="1.284" delta="+12,4% no período" tone="purple"/><Card label="Taxa de conversão" value="2,81%" delta="+0,4 ponto" tone="orange"/><Card label="Ticket médio" value="R$ 272,90" delta="Pedidos atribuídos" tone="red"/></section><section className="grid-two"><div className="panel"><PanelHead title="Receita por canal"/><div className="bars">{[['Meta Ads',58],['Google Ads',31],['Direto',11]].map(([n,v])=><div className="bar" key={n}><span>{n}</span><i><b style={{width:`${v}%`}}/></i><strong>{v}%</strong></div>)}</div></div><div className="panel"><PanelHead title="Qualidade do tracking"/><div className="quality"><div><strong>86%</strong><span>das vendas com origem identificada</span></div><ul><li><i className="ok"/>UTMs válidas <b>91%</b></li><li><i className="warn"/>Sem campanha <b>7%</b></li><li><i className="bad"/>Sem sessão <b>2%</b></li></ul></div></div></section><Sales compact/></>}
function PanelHead({title}:{title:string}){return <div className="panel-head"><h2>{title}</h2><button>Ver detalhes</button></div>}
function Sales({compact=false}:{compact?:boolean}){return <section className="panel sales"><PanelHead title={compact?'Vendas recentes':'Vendas rastreadas'}/>{!compact&&<Filters/>}<div className="table-wrap"><table><thead><tr><th>Data</th><th>Pedido</th><th>Canal</th><th>Campanha</th><th>Criativo</th><th>Receita</th><th>Status</th></tr></thead><tbody>{demo.map(r=><tr key={r.id}><td>{r.date}</td><td><b>{r.order}</b></td><td>{r.channel}</td><td>{r.campaign}</td><td>{r.creative}</td><td><b>{money(r.revenue)}</b></td><td><em className={r.status==='Atribuída'?'success':'muted'}>{r.status}</em></td></tr>)}</tbody></table></div></section>}
function Dimension({kind}:{kind:string}){return <><header className="page-title"><div><span>Marketing</span><h1>{kind}</h1><p>Compare receita, sessões e conversão por {kind.toLowerCase()}.</p></div></header><Filters/><section className="metrics"><Card label="Receita atribuída" value="R$ 818,70"/><Card label="Pedidos" value="3" tone="purple"/><Card label="ROAS" value="—" delta="Conecte custos de mídia" tone="orange"/></section><section className="panel"><Empty title={`Análise de ${kind.toLowerCase()} pronta`} copy="Os dados reais aparecem assim que o script de tracking e o webhook estiverem ativos."/></section></>}
function Diagnostics(){return <><header className="page-title"><div><span>Tracking</span><h1>Diagnóstico</h1><p>Status da captura, integrações e qualidade dos dados.</p></div></header><section className="status-grid">{[['Endpoint de captura','Aguardando deploy','warn'],['Webhook Nuvemshop','Credenciais pendentes','warn'],['Supabase','Variáveis pendentes','warn'],['Script da loja','Não instalado','bad']].map(([a,b,c])=><div className="status" key={a}><i className={c}/><div><strong>{a}</strong><span>{b}</span></div></div>)}</section><section className="panel checklist"><PanelHead title="Checklist de ativação"/><ol><li><b>Aplicar migração no Supabase</b><span>Cria sessões, eventos, pedidos e atribuições com RLS.</span></li><li><b>Configurar variáveis na Vercel</b><span>Chaves de servidor nunca ficam expostas no navegador.</span></li><li><b>Registrar webhook order/paid</b><span>Assinatura validada e processamento idempotente.</span></li><li><b>Instalar script na Nuvemshop</b><span>Captura UTMs, click IDs e sessão sem PII.</span></li></ol></section></>}
function Sessions(){return <><header className="page-title"><div><span>Tracking</span><h1>Sessões</h1><p>Jornadas capturadas desde a primeira entrada até a compra.</p></div></header><section className="panel"><Empty title="Nenhuma sessão recebida" copy="Publique o endpoint e instale o script da loja para começar a coleta."/></section></>}
function Finance(){return <><header className="page-title"><div><span>Flora Kids</span><h1>Dashboard financeiro</h1><p>Relatório financeiro original preservado durante a evolução.</p></div></header><iframe className="legacy-frame" title="Dashboard financeiro Flora Kids" src="/legacy-finance.html"/></>}

const groups=[{label:'Principal',items:[['/','Dashboard',LayoutDashboard],['/historico','Histórico',Clock3]]},{label:'Marketing',items:[['/marketing','Visão geral',BarChart3],['/marketing/canais','Canais',Users],['/marketing/campanhas','Campanhas',Tag],['/marketing/criativos','Criativos',MousePointerClick],['/marketing/vendas','Vendas rastreadas',ShoppingBag]]},{label:'Tracking',items:[['/tracking/sessoes','Sessões',Radio],['/tracking/diagnostico','Diagnóstico',Activity]]}];
function Shell(){const [open,setOpen]=useState(false);const loc=useLocation();const title=useMemo(()=>groups.flatMap(g=>g.items).find(x=>x[0]===loc.pathname)?.[1]||'EcomReports',[loc]);return <div className="app"><aside className={open?'open':''}><div className="brand"><div>F</div><span><b>EcomReports</b><small>Flora Kids</small></span><button onClick={()=>setOpen(false)}><X/></button></div><nav>{groups.map(g=><div className="nav-group" key={g.label}><label>{g.label}</label>{g.items.map(([to,name,Icon])=><NavLink end={to==='/'} to={to as string} key={to as string} onClick={()=>setOpen(false)}><Icon/><span>{name as string}</span></NavLink>)}</div>)}</nav><div className="sidebar-bottom"><NavLink to="/configuracoes"><Settings/>Configurações</NavLink><div className="user"><div>FK</div><span><b>Flora Kids</b><small>Administrador</small></span></div></div></aside><main><div className="mobile-head"><button onClick={()=>setOpen(true)}><Menu/></button><b>{title as string}</b><span/></div><div className="content"><Routes><Route path="/" element={<Finance/>}/><Route path="/historico" element={<Finance/>}/><Route path="/marketing" element={<Overview/>}/><Route path="/marketing/canais" element={<Dimension kind="Canais"/>}/><Route path="/marketing/campanhas" element={<Dimension kind="Campanhas"/>}/><Route path="/marketing/criativos" element={<Dimension kind="Criativos"/>}/><Route path="/marketing/vendas" element={<><header className="page-title"><div><span>Marketing</span><h1>Vendas rastreadas</h1><p>Pedidos da Nuvemshop associados à origem de marketing.</p></div></header><Sales/></>}/><Route path="/tracking/sessoes" element={<Sessions/>}/><Route path="/tracking/diagnostico" element={<Diagnostics/>}/><Route path="*" element={<Diagnostics/>}/></Routes></div></main>{open&&<button className="scrim" onClick={()=>setOpen(false)}/>}</div>}
export function App(){return <Shell/>}
