import {useEffect,useMemo,useState} from 'react';
import {Bar,BarChart,CartesianGrid,Cell,Legend,Pie,PieChart,ResponsiveContainer,Tooltip,XAxis,YAxis} from 'recharts';
import {CalendarDays,ChevronDown,PackageOpen,RefreshCw,Trophy} from 'lucide-react';
import {supabase} from './lib/supabase';

type Report=Record<string,any>&{id:number;type:string;period:string;ds:string;de?:string;rg?:number;rl?:number;rd?:number;to?:number;rd2?:number;ca?:number;cv?:number};
const brl=(n:number)=>n.toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const n=(v:unknown)=>Number(v)||0;
const labelType=(v:string)=>({daily:'Diário',weekly:'Semanal',monthly:'Mensal'}[v]||v);

function Kpi({label,value,tone='mint'}:{label:string;value:string;tone?:string}){return <article className="finance-kpi"><span>{label}</span><strong className={tone}>{value}</strong></article>}
export function FinancialDashboard(){
 const [reports,setReports]=useState<Report[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const [type,setType]=useState(''),[year,setYear]=useState(''),[month,setMonth]=useState(''),[from,setFrom]=useState(''),[to,setTo]=useState('');
 const load=async()=>{setLoading(true);setError('');const result=await supabase!.from('reports').select('*').order('ds',{ascending:false});if(result.error)setError(result.error.message);else setReports((result.data||[]) as Report[]);setLoading(false)};
 useEffect(()=>{load()},[]);
 const years=useMemo(()=>[...new Set(reports.map(r=>r.ds?.slice(0,4)).filter(Boolean))].sort().reverse(),[reports]);
 const data=useMemo(()=>reports.filter(r=>{const start=new Date(`${r.ds}T12:00:00`),end=new Date(`${r.de||r.ds}T12:00:00`);if(type&&r.type!==type)return false;if(year&&start.getFullYear()!==+year&&end.getFullYear()!==+year)return false;if(month&&start.getMonth()+1!==+month&&end.getMonth()+1!==+month)return false;if(from&&r.ds<from)return false;if(to&&(r.de||r.ds)>to)return false;return true}),[reports,type,year,month,from,to]);
 const totals=useMemo(()=>{const sum=(key:string)=>data.reduce((s,r)=>s+n(r[key]),0);return{gross:sum('rg'),net:sum('rl'),orders:sum('to'),supplier:sum('rd'),returns:sum('rd2'),abandoned:sum('ca'),recovered:sum('cv'),shipping:data.reduce((s,r)=>s+[1,2,3,4,5,6,7].reduce((x,i)=>x+n(r[`s${i}`]?.v),0),0)}},[data]);
 const best=data.length?[...data].sort((a,b)=>n(b.rg)-n(a.rg))[0]:null;
 const revenue=[...data].sort((a,b)=>a.ds.localeCompare(b.ds)).slice(-10).map(r=>({name:r.period?.length>14?r.period.slice(0,14)+'…':r.period,Bruto:n(r.rg),Líquido:n(r.rl)}));
 const pay=[{name:'PIX',value:data.reduce((s,r)=>s+n(r.p1o),0),color:'#16d9a6'},{name:'Cartão de crédito',value:data.reduce((s,r)=>s+n(r.p2o)+n(r.p3o)+n(r.p4o),0),color:'#60a5fa'},{name:'Débito',value:data.reduce((s,r)=>s+n(r.p5o),0),color:'#a78bfa'},{name:'Boleto / espécie',value:data.reduce((s,r)=>s+n(r.p6o)+n(r.p7o)+n(r.p8o),0),color:'#f59e0b'}].filter(x=>x.value>0);
 const motives=[['m1','Defeituoso'],['m2','Diferente do anúncio'],['m3','Arrependimento'],['m4','Atraso na entrega'],['m5','Não chegou'],['m6','Tamanho / cor'],['m7','Outros']].map(([k,name])=>({name,value:data.reduce((s,r)=>s+n(r[k]?.n),0)}));const maxM=Math.max(...motives.map(x=>x.value),1);
 const clear=()=>{setType('');setYear('');setMonth('');setFrom('');setTo('')};
 return <><header className="page-title finance-title"><div><span>Flora Kids</span><h1>Dashboard financeiro</h1><p>{loading?'Carregando dados…':`${data.length} relatório${data.length===1?'':'s'} no período selecionado`}</p></div><button className="refresh" onClick={load}><RefreshCw/> Atualizar</button></header>
 <div className="finance-filters"><label><select value={type} onChange={e=>setType(e.target.value)}><option value="">Todos os tipos</option><option value="daily">Diário</option><option value="weekly">Semanal</option><option value="monthly">Mensal</option></select><ChevronDown/></label><label><select value={year} onChange={e=>setYear(e.target.value)}><option value="">Todos os anos</option>{years.map(y=><option key={y}>{y}</option>)}</select><ChevronDown/></label><label><select value={month} onChange={e=>setMonth(e.target.value)}><option value="">Todos os meses</option>{['Janeiro','Fevereiro','Março','Abril','Maio','Junho','Julho','Agosto','Setembro','Outubro','Novembro','Dezembro'].map((x,i)=><option value={i+1} key={x}>{x}</option>)}</select><ChevronDown/></label><label className="date"><CalendarDays/><input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label className="date"><CalendarDays/><input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label><button onClick={clear}>Limpar</button></div>
 {error&&<div className="finance-warning">Não foi possível carregar os relatórios: {error}</div>}
 {!loading&&!error&&reports.length===0?<div className="panel empty"><PackageOpen/><h3>Nenhum relatório cadastrado</h3></div>:<><section className="finance-kpis"><Kpi label="Faturamento bruto" value={brl(totals.gross)}/><Kpi label="Faturamento líquido" value={brl(totals.net)}/><Kpi label="Pedidos" value={String(totals.orders)} tone="white"/><Kpi label="Ticket médio" value={brl(totals.orders?totals.gross/totals.orders:0)} tone="white"/><Kpi label="Fornecedor (custo)" value={brl(totals.supplier)} tone="orange"/><Kpi label="Frete total" value={brl(totals.shipping)} tone="purple"/><Kpi label="Devoluções" value={String(totals.returns)} tone="red"/><Kpi label="Taxa de recuperação" value={`${totals.abandoned?(totals.recovered/totals.abandoned*100).toFixed(1):'0.0'}%`} tone="purple"/></section>
 {data.length===0?<div className="finance-warning">Nenhum relatório encontrado para este filtro.</div>:<><section className="best-period"><Trophy/><div><span>Melhor período registrado</span><strong>{best?.period}</strong><small>{brl(n(best?.rg))} · {n(best?.to)} pedidos · {labelType(best?.type||'')}</small></div></section><section className="finance-charts"><div className="panel chart-panel"><h2>Faturamento bruto vs. líquido</h2><ResponsiveContainer width="100%" height={290}><BarChart data={revenue}><CartesianGrid stroke="#1b2824" vertical={false}/><XAxis dataKey="name" stroke="#64736e" fontSize={10}/><YAxis stroke="#64736e" fontSize={10} tickFormatter={v=>`R$${Math.round(v/1000)}k`}/><Tooltip contentStyle={{background:'#101715',border:'1px solid #26352f',borderRadius:8}} formatter={(v:number)=>brl(v)}/><Legend/><Bar dataKey="Bruto" fill="#14c89a" radius={[4,4,0,0]}/><Bar dataKey="Líquido" fill="#185b49" radius={[4,4,0,0]}/></BarChart></ResponsiveContainer></div><div className="panel chart-panel"><h2>Formas de pagamento</h2><ResponsiveContainer width="100%" height={290}><PieChart><Pie data={pay} dataKey="value" nameKey="name" innerRadius={72} outerRadius={105} paddingAngle={2}>{pay.map(x=><Cell key={x.name} fill={x.color}/>)}</Pie><Tooltip contentStyle={{background:'#101715',border:'1px solid #26352f',borderRadius:8}}/><Legend/></PieChart></ResponsiveContainer></div></section><section className="finance-charts lower"><div className="panel chart-panel"><h2>Carrinhos</h2><div className="cart-summary"><div><span>Abandonados</span><strong className="red">{totals.abandoned}</strong></div><div><span>Recuperados</span><strong className="mint">{totals.recovered}</strong></div><div><span>Conversão</span><strong>{totals.abandoned?(totals.recovered/totals.abandoned*100).toFixed(1):'0'}%</strong></div></div></div><div className="panel chart-panel"><h2>Motivos de devolução</h2><div className="motive-bars">{motives.map(x=><div key={x.name}><span>{x.name}</span><i><b style={{width:`${x.value/maxM*100}%`}}/></i><strong>{x.value}</strong></div>)}</div></div></section></>}</>}</>;
}
