import {useEffect,useMemo,useState} from 'react';
import {Bar,BarChart,CartesianGrid,Cell,Legend,Pie,PieChart,ResponsiveContainer,Tooltip,XAxis,YAxis} from 'recharts';
import {CalendarDays,ChevronDown,PackageOpen,Percent,RefreshCw,ShoppingBag,Trophy} from 'lucide-react';
import {apiFetch} from './lib/api';

type DashboardData={range:{from:string;to:string};metrics:{gross:number;orders:number;shipping:number;ticket:number;refunded:number};daily:{date:string;gross:number;orders:number;shipping:number}[];payments:{name:string;value:number;orders:number}[];syncedAt:string};
const brl=(n:number)=>n.toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const iso=(d:Date)=>{const y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,'0'),day=String(d.getDate()).padStart(2,'0');return `${y}-${m}-${day}`};
const range=(preset:string)=>{const end=new Date(),start=new Date(end);if(preset==='today')return{from:iso(end),to:iso(end)};if(preset==='week')start.setDate(end.getDate()-6);else if(preset==='year')start.setMonth(0,1);else start.setDate(1);return{from:iso(start),to:iso(end)}};
const colors=['#19d3a2','#60a5fa','#a78bfa','#f59e0b','#f97316','#ef5b65'];
function Kpi({label,value,tone='mint',children}:{label:string;value:string;tone?:string;children?:React.ReactNode}){return <article className="finance-kpi"><span>{label}</span><strong className={tone}>{value}</strong>{children}</article>}

export function FinancialDashboard(){
 const initial=range('month');const [preset,setPreset]=useState('month'),[from,setFrom]=useState(initial.from),[to,setTo]=useState(initial.to),[data,setData]=useState<DashboardData|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const [supplierPct,setSupplierPct]=useState(()=>Number(localStorage.getItem('supplier_cost_pct')||70));
 const load=async()=>{setLoading(true);setError('');try{const r=await apiFetch(`/api/dashboard?from=${from}&to=${to}`);const body=await r.json();if(!r.ok)throw new Error(body.error||'sync_failed');setData(body)}catch{setError('Não foi possível sincronizar os pedidos da Nuvemshop.')}finally{setLoading(false)}};
 useEffect(()=>{load()},[from,to]);
 const choose=(value:string)=>{setPreset(value);const r=range(value);setFrom(r.from);setTo(r.to)};
 const setPct=(value:number)=>{const safe=Math.min(100,Math.max(0,value||0));setSupplierPct(safe);localStorage.setItem('supplier_cost_pct',String(safe))};
 const m=data?.metrics||{gross:0,orders:0,shipping:0,ticket:0,refunded:0};const supplier=m.gross*supplierPct/100,net=m.gross-supplier;
 const chart=useMemo(()=>data?.daily.map(x=>({...x,label:new Date(`${x.date}T12:00`).toLocaleDateString('pt-BR',{day:'2-digit',month:'2-digit'}),net:x.gross*(1-supplierPct/100)}))||[],[data,supplierPct]);
 return <><header className="page-title finance-title"><div><span>Nuvemshop · dados sincronizados</span><h1>Dashboard financeiro</h1><p>{loading?'Atualizando pedidos…':data?`Atualizado ${new Date(data.syncedAt).toLocaleString('pt-BR')}`:'Aguardando sincronização'}</p></div><button className="refresh" onClick={load} disabled={loading}><RefreshCw className={loading?'spin':''}/> Atualizar</button></header>
 <div className="finance-filters"><label><select value={preset} onChange={e=>choose(e.target.value)}><option value="today">Hoje</option><option value="week">Últimos 7 dias</option><option value="month">Este mês</option><option value="year">Este ano</option><option value="custom">Personalizado</option></select><ChevronDown/></label><label className="date"><CalendarDays/><input type="date" value={from} onChange={e=>{setPreset('custom');setFrom(e.target.value)}}/></label><label className="date"><CalendarDays/><input type="date" value={to} onChange={e=>{setPreset('custom');setTo(e.target.value)}}/></label></div>
 {error&&<div className="finance-warning">{error}</div>}
 {!loading&&!error&&data&&m.orders===0?<div className="panel empty"><PackageOpen/><h3>Nenhum pedido pago neste período</h3><p>Altere o filtro de datas para consultar outro intervalo.</p></div>:<><section className="finance-kpis"><Kpi label="Faturamento bruto" value={brl(m.gross)}/><Kpi label="Faturamento líquido" value={brl(net)}/><Kpi label="Pedidos pagos" value={String(m.orders)} tone="white"/><Kpi label="Ticket médio" value={brl(m.ticket)} tone="white"/><Kpi label="Fornecedor (custo)" value={brl(supplier)} tone="orange"><label className="pct-input"><Percent/><input type="number" min="0" max="100" value={supplierPct} onChange={e=>setPct(Number(e.target.value))}/></label></Kpi><Kpi label="Frete cobrado" value={brl(m.shipping)} tone="purple"/><Kpi label="Reembolsos" value={String(m.refunded)} tone="red"/><Kpi label="Margem após fornecedor" value={`${(100-supplierPct).toFixed(1)}%`} tone="purple"/></section>
 <section className="best-period"><Trophy/><div><span>Fonte dos dados</span><strong>Pedidos pagos da Nuvemshop</strong><small>Cancelados e totalmente reembolsados não entram no faturamento.</small></div></section><section className="finance-charts"><div className="panel chart-panel"><h2>Faturamento bruto vs. líquido</h2><ResponsiveContainer width="100%" height={290}><BarChart data={chart}><CartesianGrid stroke="#1b2824" vertical={false}/><XAxis dataKey="label" stroke="#64736e" fontSize={10}/><YAxis stroke="#64736e" fontSize={10} tickFormatter={v=>`R$${Math.round(v/1000)}k`}/><Tooltip contentStyle={{background:'#101715',border:'1px solid #26352f',borderRadius:8}} formatter={(v:number)=>brl(v)}/><Legend/><Bar dataKey="gross" name="Bruto" fill="#14c89a" radius={[4,4,0,0]}/><Bar dataKey="net" name="Líquido" fill="#185b49" radius={[4,4,0,0]}/></BarChart></ResponsiveContainer></div><div className="panel chart-panel"><h2>Faturamento por pagamento</h2><ResponsiveContainer width="100%" height={290}><PieChart><Pie data={data?.payments||[]} dataKey="value" nameKey="name" innerRadius={72} outerRadius={105} paddingAngle={2}>{data?.payments.map((x,i)=><Cell key={x.name} fill={colors[i%colors.length]}/>)}</Pie><Tooltip contentStyle={{background:'#101715',border:'1px solid #26352f',borderRadius:8}} formatter={(v:number)=>brl(v)}/><Legend/></PieChart></ResponsiveContainer></div></section><section className="finance-charts lower"><div className="panel chart-panel"><h2>Resumo operacional</h2><div className="cart-summary"><div><span>Pedidos pagos</span><strong className="mint">{m.orders}</strong></div><div><span>Frete cobrado</span><strong>{brl(m.shipping)}</strong></div><div><span>Ticket médio</span><strong>{brl(m.ticket)}</strong></div></div></div><div className="panel chart-panel sync-explainer"><ShoppingBag/><div><h2>Sincronização automática</h2><p>Os números são recalculados diretamente dos pedidos da Nuvemshop sempre que você abre ou atualiza esta tela.</p></div></div></section></>}</>;
}
